# Generated by Django 4.2 on 2023-05-05 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("choice_thuja", models.CharField(db_index=True, max_length=200)),
                (
                    "slug",
                    models.SlugField(max_length=250, unique=True, verbose_name="URL"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tui",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="сорт")),
                (
                    "slug",
                    models.SlugField(max_length=250, unique=True, verbose_name="URL"),
                ),
                ("content", models.TextField(blank=True, verbose_name="описание")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="цена"
                    ),
                ),
                (
                    "availability",
                    models.BooleanField(default=True, verbose_name="доступность"),
                ),
                (
                    "choice",
                    models.CharField(
                        choices=[
                            ("туя", "туи"),
                            ("сосна", "сосны"),
                            ("можж", "можжевельники"),
                            ("куст", "кустарники"),
                            ("плод", "плодоввые"),
                            ("цвет", "цветы"),
                            ("штамб", "штамбовые"),
                            ("ель", "ели"),
                            ("смесь", "смесь"),
                        ],
                        default="смесь",
                        max_length=20,
                        verbose_name="выбор раздела",
                    ),
                ),
                ("image", models.ImageField(upload_to="photos", verbose_name="фото")),
                ("amount", models.IntegerField(default=1, verbose_name="кол-во")),
                (
                    "thuja_cat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="main_page.category",
                        verbose_name="категории",
                    ),
                ),
            ],
            options={
                "verbose_name": "Список туй",
                "verbose_name_plural": "Список туй",
            },
        ),
    ]
