# Generated by Django 4.2 on 2023-05-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_page", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Категории", "verbose_name_plural": "Категории"},
        ),
        migrations.AlterField(
            model_name="tui",
            name="choice",
            field=models.CharField(
                choices=[
                    ("туя", "туи"),
                    ("сосна", "сосны"),
                    ("можж", "можжевельники"),
                    ("куст", "кустарники"),
                    ("плод", "плодоввые"),
                    ("цвет", "цветы"),
                    ("штамб", "штамбовые"),
                    ("ель", "ели"),
                    ("смесь", "смесь"),
                    ("Деревья", "Деревья"),
                ],
                default="смесь",
                max_length=20,
                verbose_name="выбор раздела",
            ),
        ),
    ]
